# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(max_length=250)),
                ('clue_number', models.PositiveIntegerField()),
                ('answer_length', models.PositiveIntegerField()),
                ('across_down', models.PositiveIntegerField()),
                ('cell_number', models.PositiveIntegerField()),
            ],
        ),
    ]
